### PR TITLE
Use deterministic names for dataframe 

### LINKED ISSUE #505: Use meaningful tokens in dask.dataframe
For caching to work well we need to use meaningful tokens in names.  This means replacing keys like 

    ('read_csv-123', 3) 

with 

    ('read_csv-myfile.csv', 3)

Now anytime someone uses `read_csv('myfile.csv')` they should get mapped to the same set of keys.  Of course, this is overly simplistic because we also have to include information about keyword arguments and such.  

Ideally we do this everywhere within all of the collections.  I intend to start on dataframe as a test case.  I intend to use `md5` on string representations of arugments and keywords for leaf functions like `read_csv` and then to use `md5` on the names of input dataframes for non-leaf functions working upward.

### PR DESCRIPTION
**Pull request by mrocklin**
Every collection has a name that the top-level/root nodes of the dask graph

```python
>>> df._name
'df-123'
>>> df.dask
{('df-123', 0): ...,
 ('df-123', 1): ...,
 ('read-csv-44', 0): ..., }
```

Currently these names usually consist of an operation name, like `concat` or `read_csv` along with an auto-incrementing number.  This is simple but means that equivalent dataframes don't have the same name.

```python
>>> dd.read_csv('myfile.csv')._name
'read_csv-123'
>>> dd.read_csv('myfile.csv')._name
'read_csv-124'
```

This limits our ability to perform meaningful caching (see #502).

To resolve this we introduce deterministic names that are generally an `md5` hash of necessary identifiers of the inputs to the operation.

```python
>>> dd.read_csv('myfile.csv')._name
'read_csv-1234FEDC'
>>> dd.read_csv('myfile.csv')._name  # same name
'read_csv-1234FEDC'
>>> dd.read_csv('myfile.csv', skiprows=1)._name  # different name
'read_csv-FFFF4321'
```

This will require some care and probably a full pass over the dataframe code.  So far it doesn't seem too complicated.  Feedback welcome on this idea before I go ahead.  This adds a slight burden on future dataframe development work.  We need to explicitly think about all inputs that might affect the output, turn those into a string and send them to a hash function.

Fixes #505

### CODE REVIEW

**Comment by wrobstory** [comment]
`This adds a slight burden on future dataframe development work.`

Is the following statement correct: "any change in input arguments should result in a new unique identifier"? If so, maybe there could be a standard decorator for every method that captures all the arguments, compares equality, and renames? That could help a bit with the burden; the rule would be that each new aggregator needs to be wrapped with the decorator and assigned a unique token name.

Also, while we're talking about future development ease, it might be useful to register tokens with the enclosing class and then have a unit test check token uniqueness.

**Comment by TomAugspurger** [comment]
As an example, what's the caching story of the following three:

```python
# operation 1. cache this
>>> df.std()
# Operation 2: calculation then rename
>>> df.std().rename(columns={'A': 'a', 'B': 'b'})  # once I finish my rename PR
# Operation 3: rename then calculate
>>> df.rename(columns={'A': 'a', 'B': 'b'}).std()
```

I haven't had a chance to read the code yet, so I don't have any answers on what happens right now (I'd guess that operation 2 uses the cached `.std`, but 3 doesn't.), and I haven't thought much about whether 3 *should* be able to use the cache, since (only) the labels have changed. But there are probably cases where the labels changing *do* matter (joins come to mind). Sorry for not being helpful yet, just thoughts.

**Comment by mrocklin** [comment]
We won't end up mapping semantically similar but syntactically different operations to the same name.  These will be cached separately.

At the moment most functions (like `rename` and `std`) create new names based on their input names and other input arguments.  Name creation uses `md5` which won't persist any useful symmetries.

**Comment by mrocklin** [comment]
I've rewritten dask.dataframe so that all use of the `tokens` iterator from before is gone, replaced either with hashed names or with uuids.

**Comment by mrocklin** [comment]
> Is the following statement correct: "any change in input arguments should result in a new unique identifier"? If so, maybe there could be a standard decorator for every method that captures all the arguments, compares equality, and renames?

I've found that I've wanted to do things a bit specially often enough that picking out the data to hash by hand has been useful.  For example in `read_csv` we really want to include the result of `os.path.getmtime` on the filename.  The current approach is to collect all of the relevant data into a tuple and then pass that into the `tokenize` function.  This has worked fairly well so far.

**Comment by mrocklin** [comment]
@shoyer as per your previous tweet I now plan to go through dask.array doing the same thing.  

Your feedback here to make sure that this is a good approach would be welcome.

**Comment by mrocklin** [comment]
I plan to merge this in 24 hours if no comment.

**Comment by shoyer** [comment]
This seems pretty sane to me. `os.path.getmtime` removes one of my major concerns -- we'll want to include that when we generate tokens for array names in xray.

**Pull request merged**
