### PR TITLE
Use array-overview.rst as dask array's README

### PR DESCRIPTION
**Pull request by cowlicks**
I think having a README in dask array would be useful for people browsing the project on github. This duplicates the file `das/docs/source/array-overview.rst`. I could do this for the other collections and schedulers if this is received well.

### CODE REVIEW

**Comment by mrocklin** [comment]
Is there a way to link within a git repository?  One of these documents will inevitably become stale.

**Comment by shoyer** [comment]
You can check soft links into git... not sure if either of GitHub or ReadTheDocs handle those well, though.

**Comment by minrk** [comment]
Relative URLs work in rendered pages on GitHub, so you can have `[the docs](../docs)`, etc in markdown.

**Comment by mrocklin** [comment]
Closing this for now; I don't see an immediate need for this.

**Pull request closed without merging**
