### PR TITLE
Fix GH #472: Add proper arity detection for builtins and constructors

### PR DESCRIPTION
**Pull request by StuartAxelOwen**
Fix GH #472: Add proper arity detection for builtins and constructors

### CODE REVIEW

**Comment by mrocklin** [comment]
Not sure what our plans are with #472 but if we plan to go along with it then this would be useful.  I might suggest that `takes_multiple_arguments` gets moved into `dask/utils.py` because it seems to be getting a bit intense.  I'm curious what was the driving motivation behind specializing all of the builtins?

**Comment by StuartAxelOwen** [comment]
`inspect.getargspec` can't inspect any builtins, so I figured I would classify all the builtins I could every see anyone reasonably using.  I'll move `takes_multiple_arguments` into `dask/utils.py` as suggested.

**Comment by mrocklin** [comment]
@StuartAxelOwen are you still intending to move forward with this?  I can take it over if not.

**Comment by StuartAxelOwen** [comment]
Yes, I'll take care of it today.

**Comment by jcrist** [comment]
In this system, what does the following do?

```python
>>> seq = [([[4, 5, 6], [7, 8, 9]], [1, 2, 3]),
...        ([[4, 5, 6], [7, 8, 9]], [1, 2, 3]),
...        ([[4, 5, 6], [7, 8, 9]], [1, 2, 3])]
>>> b = db.from_sequence(seq)
>>> b.map(sum).compute()
```

Does it splat into the two arg form of `sum`, resulting in `[1, 2, 3, 4, 5, 6, 7, 8, 9]`? Or does it error, trying to sum a list and an int? I really don't see how this can be done in a robust way where you can be certain it will perform one operation or another. This fails on partials, numba-fied functions, any not included c functions, cythonized code, etc...

**Comment by mrocklin** [comment]
This example falls into the "don't guess on clearly ambiguous situations, rather assume single input" category.  The proposed solution from the conversation in #472 (as I understand it) is to only splat when it's obvious, as in the case of `lambda a, b: ...`

**Comment by StuartAxelOwen** [comment]
It will type error.  The way `takes_multiple_arguments` works currently, it assumes that functions with one required arg are single arity, `sum` being one of those.  (It was this way before this change)

Really, the core problem with the case you're talking about is that Python doesn't make strong enough contracts in it's function signatures for this kind of introspection to be reliable.  To be 100% sure that the user can achieve the amount of splatting they want, you'd have to give them a function param for it.

Anyway, this change isn't necessarily related to map, as it only improves the `takes_multiple_arguments` function's accuracy.

**Comment by StuartAxelOwen** [comment]
Aight, moved `takes_multiple_arguments` into `dask.util` and added/updated its tests.  Sorry for the delay.

**Comment by mrocklin** [comment]
He who does the work has full control over the timing as far as I'm concerned.  Checking this out now

**Comment by mrocklin** [comment]
I added a final style commit and have merged this.  Thank you both for the bug report and for the fix @StuartAxelOwen !

**Pull request merged**
