### PR TITLE
Added `merge_sync` and `sync_keys`

### LINKED ISSUE #37: Synchronize keys between two dasks
Given two dasks

```python
d = {'a': 1, 'b': (add, 'a', 10), 'c': (mul, 'b', 5)}
e = {'x': 1, 'y': (add, 'x', 10), 'z': (mul, 'y', 2)}
```

We may want to merge them in a way that is blind to renamings of variables.

```python
>>> merge_sync(d, e)
{'a': 1, 'b': (add, 'a', 10), 'c': (mul, 'b', 5), 'z': (mul, 'b', 2)}
```

I think that @eriknw may have brought up this idea before.  I now have a driving use case for it and find it very valuable.

I'm not sure of the best way to design this.  It might be best to have a merge function like above or perhaps just a synchronize names function that is orthogonal to merging.

### PR DESCRIPTION
**Pull request by jcrist**
Allows for syncing dasks together, removing terms equivalent modulo
variables. Fixes #37.

This provides two functions: `sync_vars` and `merge_sync`:
- `sync_vars` takes two dasks, and returns a `dict` mapping keys in `dask2` to equivalent keys in `dask1`.
- `merge_sync` takes two dasks, calls `sync_vars`, and then merges the two dasks, applying the substitutions to each task.

If a term doesn't support `==`, it is skipped over.

Example:

```
>>> dsk1 = {'a': 1, 'b': (add, 'a', 10), 'c': (mul, 'b', 5)}
>>> dsk2 = {'x': 1, 'y': (add, 'x', 10), 'z': (mul, 'y', 2)}
>>> sync_vars(dsk1, dsk2)
{'x': 'a', 'y': 'b'}
>>> merge_sync(dsk1, dsk2)
{'a': 1, 'b': (add, 'a', 10), 'c': (mul, 'b', 5), 'z': (mul, 'b', 2)}
```

### CODE REVIEW

**Comment by jcrist** [comment]
This won't work for dasks that have matching keys (i.e. both dasks have key `'a'`). I'm not sure how best to handle that. I see two solutions to this:

1. We create a new unique key for name conflicts. However, this will cause issues if that key is a desired result, as it won't be in the dask anymore. One solution would be to return a mapping of old names in dask2 to their new names in the merged dask. Note that this may be necessary even without name conflicts if any keys are replaced. Example:

```
>>> dsk1 = {'a': 1}
>>> dsk2 = {'a': 2}
>>> new_dsk, mapping = merge_sync(dsk1, dsk2)
>>> new_dsk
{'a': 1, 'gensym_1': 2}
>>> mapping
{'a': 'gensym_1'}
```

2. Erroring on name conflicts if the corresponding values aren't equivalent. Example:

```
>>> dsk1 = {'a': 1}
>>> dsk2 = {'a': 2}
>>> merge_sync(dsk1, dsk2)
ValueError("Conflicting keys in dsk1 and dsk2")
>>> merge_sync(dsk1, dsk1)
{'a': 1}
```

Thoughts?

**Comment by mrocklin** [comment]
```
>>> dsk1 = {'a': 1, 'b': (add, 'a', 10), 'c': (mul, 'b', 5)}
>>> dsk2 = {'x': 1, 'y': (add, 'x', 10), 'z': (mul, 'y', 2)}
>>> sync_vars(dsk1, dsk2)
{'x': 'a', 'y': 'b'}
```
How would this handle redundancy within a dask?, e.g `{'a': 1, 'b': 1, ...}`

**Comment by mrocklin** [comment]
As you point out it might be important to respect the names of a certain set of output keys.  It might make sense to take these as another input.

**Comment by jcrist** [comment]
> How would this handle redundancy within a dask?, e.g {'a': 1, 'b': 1, ...}

Right now it just finds the first valid match. The order of what's checked has to do with the ordering of `dsk1.keys()`, so it's random. I'm not sure if dealing with such cases is in the scope of this function - a good way to avoid this would be to trim duplicates from `dsk1` before calling. Terms in `dsk2` will always match to the same value in `dsk1`, so there's maybe no need to deduplicate `dsk2` (it won't remove duplicate terms that don't match something in `dsk1` though).

>  It might make sense to take these as another input.

So have an optional arg `no_rename` (or some other name) that takes a list of variables in `dsk2` that can't be renamed? What happens in a case of conflict? Error? 

Right now I'm treating `dsk1` as concrete and only changing `dsk2`. If we can change keys in *both* dasks, then as long as the same variable name in each dask isn't requested there would always be one variable that could be renamed. However, I'm not sure how this would work with the `sync_vars` function.

I guess the question is, what is the intended scope of these functions?

**Comment by mrocklin** [comment]
A separate pass of de-duplication sounds like a good solution to redundancy within one graph.


Thinking more about this problem maybe we don't need to keep the output keys the same.  Maybe we just change the keys sent to `get` functions as we change them in dsk2.

> I guess the question is, what is the intended scope of these functions?

That's a great question.  At the moment I'm considering the case where we accumulate dask computations from previous runs and reuse them in future runs.  Ideally this benefits from overlap between multiple similar queries.  I was fooling around with this idea in https://github.com/ContinuumIO/dask/pull/36 but it hasn't gone anywhere yet.  

Consider the following example:

```python
x = da.from_array(x, blockshape=(1000,))

y = x[:5000].sum().compute()
z = x[:6000].sum().compute()
```

Most of the work for z is already done when we compute `y` if we hold on to the right intermediate results (another problem entirely.)  The shared structure in these graphs is the same except for the names.  The goal is to identify and unite these cases.  Presumably we have one large dask graph that contains everything we've seen so far (the dealiasing and merger of many dask graphs) and every time we compute something we merge it into this graph and then compute against a shared cache with values keyed by the keys within this graph.

Within this context we probably only want to change dsk2 (the smaller graph).

**Comment by jcrist** [comment]
> Maybe we just change the keys sent to get functions as we change them in dsk2.

So something like the following?

```
>>> sub_dict, key_lookup = sync_vars(dsk1, dsk2, result_keys)
>>> new_dsk, key_lookup = merge_sync(dsk1, dsk2, result_keys)
```

Where `result_keys` is a list of keys that we may request from `dsk2`, and `key_lookup` is a `dict` mapping the old `result_keys` to their (potentially) new values. I'm unsure if the change to `sync_vars` is needed, but the change for `merge_sync` sounds good to me. I feel that `sync_vars` should probably just create mappings between equivalent keys in `dsk2` and `dsk1` without considering name conflicts.

> At the moment I'm considering the case where we accumulate dask computations from previous runs and reuse them in future runs.

Interesting idea. I was playing with using it for pre-optimizing dasks before execution (no need to compute the same thing twice). If we store results in an ever size increasing dask, a permanent `dep_dict` data structure would make merging new dasks *much* faster, as we'd no longer have to preprocess `dask1` each time. The current functions don't support this (preprocessing is contained in `sync_vars`), but they could be refactored to work nicely in such situations.

---
(aside, because this is interesting)

> The goal is to identify and unite these cases.

This sounds like a pretty difficult problem to solve, as matching sub problems is *semantic* rather than *syntactic*. Assuming the task for the example you gave is:

```
(sum, (getitem, 'x', (0, 1, 6000)))    # I think that's how slice tuples work?
```

Certainly, one could search for this exact query to see if it's already been computed (syntactic matching), but other equivalent terms are:

```
(sum, (getitem, 'x', (6000, -1, 0)))
(add, (sum, 'x', (0, 1, 3000)), (sum, 'x', (3000, 1, 6000)))
```

These don't match the query term, but by meaning they're the same. And then you have subproblems like:

```
(sum, (getitem, 'x', (3000, 1, 6000)))
(sum, (getitem, 'x', (2000, 1, 4000)))
```

Because they overlap, you'd have to have some metric to determine which already solved solution should be used to reduce computation time. And if they didn't overlap, then there'd  be a way to use both of them. I'm seeing *a lot* of special case code coming from this. 

It would be really cool to get this working, but it sounds like a pretty difficult problem to solve if we're going to add knowledge about how some tasks can be sub-problems for other tasks without having them actually composed of those other tasks.

**Comment by mrocklin** [comment]
Fortunately the blocking into blocks of size `1000` saves us here.  

Sorry for the fast example without context.  I'm headed out the door.

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: x = np.arange(10000)

In [4]: x = da.from_array(x, blockshape=(1000,))

In [6]: y = x[:6000].sum()

In [7]: da.optimize(y.dask, y._keys())
Out[7]: 
{'x_1': array([   0,    1,    2, ..., 9997, 9998, 9999]),
 ('x_6', 0): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(0, 1000, None),))),
 ('x_6', 1): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(1000, 2000, None),))),
 ('x_6', 2): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(2000, 3000, None),))),
 ('x_6', 3): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(3000, 4000, None),))),
 ('x_6', 4): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(4000, 5000, None),))),
 ('x_6', 5): (<functools.partial at 0x7faa6477e940>,
  (<function operator.getitem>, 'x_1', (slice(5000, 6000, None),))),
 ('x_7',): (<toolz.functoolz.Compose at 0x7faa646c8be8>,
  [('x_6', 0), ('x_6', 1), ('x_6', 2), ('x_6', 3), ('x_6', 4), ('x_6', 5)])}

In [8]: y = x[:5000].sum()

In [9]: da.optimize(y.dask, y._keys())
Out[9]: 
{'x_1': array([   0,    1,    2, ..., 9997, 9998, 9999]),
 ('x_10',): (<toolz.functoolz.Compose at 0x7faa646c8c58>,
  [('x_9', 0), ('x_9', 1), ('x_9', 2), ('x_9', 3), ('x_9', 4)]),
 ('x_9', 0): (<functools.partial at 0x7faa646cfa48>,
  (<function operator.getitem>, 'x_1', (slice(0, 1000, None),))),
 ('x_9', 1): (<functools.partial at 0x7faa646cfa48>,
  (<function operator.getitem>, 'x_1', (slice(1000, 2000, None),))),
 ('x_9', 2): (<functools.partial at 0x7faa646cfa48>,
  (<function operator.getitem>, 'x_1', (slice(2000, 3000, None),))),
 ('x_9', 3): (<functools.partial at 0x7faa646cfa48>,
  (<function operator.getitem>, 'x_1', (slice(3000, 4000, None),))),
 ('x_9', 4): (<functools.partial at 0x7faa646cfa48>,
  (<function operator.getitem>, 'x_1', (slice(4000, 5000, None),)))}
```

**Comment by jcrist** [comment]
Ahhh, that'll make things easier. Not sure if it would be worth it memory-wise, but you could probably come up with some heuristic for cacheing only the queries that are directly related to the underlying datasets (in this case, the sum of each block), as those are the expensive computations.

Anyway, after some more thought, I think that `sync_vars` should stay the same, but the behavior of `merge_sync` should be changed to the following:

```python
def merge_sync(dsk1, dsk2):
    """Merge two dasks together, combining equivalent terms.

    Parameters
    ----------
    dsk1, dsk2 : dasks

    Returns
    -------
    new_dsk : the merged dask
    key_map : a mapping between key names in `dsk2`, and key names in `new_dsk`"""
```

This will merge the dasks, and return the dict from `sync_vars`, updated with any renames due to name conflicts.

**Comment by mrocklin** [comment]
I suspect the first heuristic will be to look at three things for each key/task pair

1.  The duration of computation (this took 200ms to compute)
2.  The size of the results in bytes
3.  How frequently this key gets requested

And then some sort of priority queue that takes the "best" keys based on some function over those things.

**Comment by mrocklin** [comment]
This seems fine to me, but I haven't taken a very in depth look.  @eriknw might find this interesting but he might be busy.

Honestly we should probably have an actual problem before we go too much more deeply in this direction.  The use case I had of slowly increasing datasets dired up a bit.  it would be a fun thing to resurrect though.  It's a novel direction for computation.

**Pull request merged**
