### PR TITLE
Add global context manager

### PR DESCRIPTION
**Pull request by mrocklin**
Supports setting get function within a with block

cc @shoyer

### CODE REVIEW

**Comment by shoyer** [comment]
It's slightly awkward to write `dask.context.context` but otherwise this looks good to me!

**Comment by mrocklin** [comment]
I'll probably pull context both into the main namespace and into `da`.  Would like to find a better name than `context` though.  Any thoughts?

**Comment by shoyer** [comment]
Perhaps `dask.set_options`?

**Comment by mrocklin** [comment]
Renamed and added set_options to the `da` namespace.

**Pull request merged**
