### PR TITLE
Coarsen

### PR DESCRIPTION
**Pull request by mrocklin**
Coarsening operation.  Efficiently applies any numpy reduction to small neighborhoods.  This includes both a numpy version and a dask version.  

This assumes that shape and block sizes line up nicely with coarsening scales which can be a significant limitation.

This would be useful for some abstract rendering techniques (cc @bryevdv) and part of multigrid (cc @maxhutch)

Example
-------

```Python
    >>> x = np.array([1, 2, 3, 4, 5, 6])
    >>> coarsen(np.sum, x, {0: 2})
    array([ 3,  7, 11])
    >>> coarsen(np.max, x, {0: 3})
    array([3, 6])

    Provide dictionary of scale per dimension

    >>> x = np.arange(24).reshape((4, 6))
    >>> x
    array([[ 0,  1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10, 11],
           [12, 13, 14, 15, 16, 17],
           [18, 19, 20, 21, 22, 23]])

    >>> coarsen(np.min, x, {0: 2, 1: 3})
    array([[ 0,  3],
           [12, 15]])
```

Dask example
-----------

```Python
Here is an example workflow and image:

Point to potentially very large dataset (although in this case quite small)

In [1]: import netCDF4

In [2]: t = netCDF4.Dataset('2014-01-01.nc3').variables['t2m']

In [3]: t.shape
Out[3]: (4, 721, 1440)

Tell dask how to block up this dataset (still no actual work done)

In [4]: import dask.array as da

In [5]: d = da.from_array(t, blockshape=(4, 90, 90))

In [6]: d = d[:, :-1, :]

In [7]: d.shape
Out[7]: (4, 720, 1440)

Coarsen by 5x5 blocks in first an second dimensions, using np.min/max on each block.

In [8]: import numpy as np

In [9]: max = da.coarsen(np.max, d, {1: 5, 2: 5})

In [10]: min = da.coarsen(np.min, d, {1: 5, 2: 5})

In [11]: max.shape
Out[11]: (4, 144, 288)

Plot (btw, bokeh should accept __array__ protocol)

In [12]: import matplotlib.pyplot as plt
In [13]: plt.imshow((max - min).mean(axis=0), cmap='RdBu_r')
```

diff

### CODE REVIEW

**Comment by maxhutch** [comment]
Very nice!  It would be nice to be able to pass a local coarsening function (e.g. np.max) that has multiple outputs.  For example, multiple each block of 6 values by a 2x6 matrix.  This is what I'd want to do for coarsening spectral element which are non-local within the element.

**Comment by mrocklin** [comment]
This particular implementation only works with functions that have the same interface as most numpy reductions `func(x, axis=...)` and return something of the shape that they would return.  I suggest that we also provide a more general `map_blocks` function that takes both a general function and a resulting shape.

**Comment by maxhutch** [comment]
Sure, as long as it looks as nice as coarsen:
```python
da.map_blocks(lambda bx: np.dot(A,bx), x, {0: (A.shape[1], A.shape[0])})
```
It is important that `map_blocks` takes block sizes as arguments, like `coarsen`, instead of just using dask's `blockshape`.

**Comment by mrocklin** [comment]
OK, merging this.  Will work on block mapping in a bit.

**Pull request merged**
