### PR TITLE
Repeated insert

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #165 

I haven't decided yet if I want to normalize out zero-sized chunks from all dask.arrays.  This feels a bit aggressive.  I can't think of a case where someone would want these chunks, but still, if someone gives them explicitly it seems odd to remove them.  Instead I've corrected the `insert` function to not make zero-sized chunks.

### CODE REVIEW

**Comment by cowlicks** [comment]
Is a "zero-sized chunk" returned by an empty slice on a dask array? Empty slices should be valid, so are these a use case?

**Comment by mrocklin** [comment]
> Is a "zero-sized chunk" returned by an empty slice on a dask array? Empty slices should be valid, so are these a use case?

Yes, by zero-sized chunk I mean chunks that might be part of an array with the following chunks attribute (aka blockdims)

    >>> a.chunks
    ((0, 5, 5, 0, 5), (1, 2, 3))

One possible solution to the presented issue was to squash all zeros in chunks on array creation.  

I'm not going ahead with that solution in this PR because I'm not certain if they should or should not be valid.

**Comment by mrocklin** [comment]
@shoyer thoughts?

**Comment by shoyer** [comment]
This looks fine to me. I agree that it's a little weird to get rid of zero-sized chunks.

**Pull request merged**
