### PR TITLE
added notebook with example of parallizing image filtering workload with dask

### PR DESCRIPTION
**Pull request by arve0**

### CODE REVIEW

**Comment by mrocklin** [comment]
This is fantastic work.  

It looks like you've avoided GIL+Serialization issues by reimplementing (or newly implementing) your algorithm using Numba and nogil mode.  Was the original scipy algorithm not releasing the GIL?

The fact that there are seams at the block boundaries indicates that something is off with overlapping.  This is likely a problem either in dask.array.ghost or in the implementation of `apply_chunks`.

You have a 2x speedup.  Why not more?  Do we know what the current bottleneck is?

**Comment by arve0** [comment]
The scikit-image implementation does not release the GIL, and I'm not familiar with Cython, so I just implemented it in numba. Much easier then patching scikit-image and compiling it (the microscope where this software is to be used is a windows machine, and installing visual studio seems a bit too much). But I guess the scikit-image folks will eventually release GIL in computation of Cython files. Seems like there is no interaction on python objects (as far as I can see), so it should be as easy as adding `with nogil:`.

The seams are not a problem, its expected when convolving an image, as all neighbor pixels are counted. Neighbor pixels are decided by the structuring element (selem). At the edges on will therefor go out of bounds in the image, depending on the size of the selem. Larger selem -> longer out of bounds -> higher `depth` to overlap. As shown in the notebook, declaring `depth` remedies the "problem". 

As for what to do when out of bounds, I pad with constant equal to the edge pixel - which is common.

Not sure why I do not have more speedup, should be ~3.5. Not sure what the bottleneck is, CPU is ~360%.

**Comment by mrocklin** [comment]
Is there a way to make make the dataset public?  It would be nice for other users to be able to execute the notebook.

We should probably also wait on https://github.com/scikit-image/scikit-image/pull/1493 before we merge so that we can clean out the setup code.

**Comment by arve0** [comment]
I've pushed the image in github and included a download in the top of the notebook. I'll clean the setup when scikit-image merges #1493.

**Comment by cowlicks** [comment]
Thanks @arve0!

**Comment by arve0** [comment]
Btw, I just though of, why not inlcude the work of @cowlicks in a utility-submodule of dask? I guess this is quite common use case for other datasets to make it general?

**Comment by mrocklin** [comment]
Most of the overlapping logic is in dask and is used in applications other than scikit-image.

Dask.array has a map_overlap function and a more low-level dask.array.ghost module.  These are our generic version of `skimage.apply_parallel` and follow interfaces more idiomatic to dask.array.  Apply_parallel was built to handle the specific needs of the scikit-image community.

**Comment by arve0** [comment]
I see. What will be the idiomatic dask-way for _get_chunks? Should I edit the notebook to use `map_overlap` directly? Seems a bit dull to have scikit-image as an dependency for a wrapper function.

**Comment by mrocklin** [comment]
You would have a dask.array to start (perhaps by using `da.from_array`), then you would all `map_overlap` with your function (putting extra args or kwargs in a lamba probably), then you would do then you would call `compute`.

**Comment by arve0** [comment]
Yes, that is clear. 

To be more precise what I meant: Is there an idiomatic way to split an array in equally sized chunks? For cpu-intensive tasks, this will be a common way to split your data, and I guess that _get_chunks could be an utility function of dask. Or even better, implement a split parameter in da.array/from_array.

**Comment by arve0** [comment]
Might be hard to implement in general for any kind of array dimensions?

**Comment by mrocklin** [comment]
Ah, my apologies, I totally misread your question. 

Dask doesn't have a `_get_chunks` equivalent.  My current stance on this is that I'm ok requiring dask.array users to think about chunk sizes.  I would much rather solve this problem with docs than with code.  It's a very hard problem to get right, particularly when you think about how ideal chunk shape depends on the computation you want to do.

**Comment by arve0** [comment]
Heh, we have quite opposite preferences then. I prefer sane defaults and not thinking :grinning: 

But fair enough, I'll create the chunks manually and add some explanation. Give me a day (have some other appointments).

**Comment by mrocklin** [comment]
I generally recommend that users just put in `chunks=1000` if they're not sure.  If you don't care about 100% efficiency not always important to get things perfectly lined up.

**Comment by cowlicks** [comment]
@arve0 part of the problem in deciding chunk size is knowing whether the function you are applying will be memory-bound or CPU-bound.

If you are CPU-bound then just break up the array int `count_cpu()` chunks. But if you are memory bound, like if you have an array that is too large to fit in memory, you would want `chunk.nbytes() * count_cpu()` to fit in memory.

**Comment by arve0** [comment]
Btw, while I have you here, can one alter the chunks after the dask.array have been created?

**Comment by cowlicks** [comment]
[`dask.array.rechunk`](https://github.com/ContinuumIO/dask/blob/master/dask/array/rechunk.py)

**Comment by mrocklin** [comment]
There is a `rechunk` method that will do all of the appropriate slicing to rearrange chunks as you like.  This does trigger (very cheap) computation though.

**Comment by arve0** [comment]
Thanks

**Comment by arve0** [comment]
What about that? Tried to keep setup to a minimum, and used the simpler mean filter as this is most for demonstration purposes.

**Comment by mrocklin** [comment]
This looks good to me.  Also, on my computer times go from 2.4s to 750ms, so I'm able to get a 3x speedup.  The difference in interactivity between 2.4s and 750ms is actually pretty big.  Everything feels a lot slicker.

Merging soon if no comment.

**Comment by arve0** [comment]
Only one note, I could also have used the `scipy.ndimage.uniform_filter`, which is equivalent to `mean` here. Scipy releases the GIL, so the performance gain should be the same. Thoughts?

**Comment by mrocklin** [comment]
Hrm, good point.  That probably does look a bit better and it would be interesting to verify that it performs well.

**Comment by arve0** [comment]
there you go!

**Comment by mrocklin** [comment]
This looks great!  Thanks @arve0 !

**Pull request merged**
