### PR TITLE
A few callback related fixes

### PR DESCRIPTION
**Pull request by jcrist**
- Make `ProgressBar` robust to change in dask graph size
- Move cache to top-level

### CODE REVIEW

**Comment by mrocklin** [comment]
I'll give this a shot when I'm next at my work machine.

**Comment by mrocklin** [comment]
[############################################] | 110% Completed |  9min  1.5s

:(

**Comment by mrocklin** [comment]
On the plus side.  Adding a call to `dealias` as you suggested earlier did resolve my issue.  I'm not sure what's going on.

**Comment by jcrist** [comment]
dammit. A test case would be nice, this passed on every workload I tried it on. Do you have `dealias` in the optimize for this?

**Comment by mrocklin** [comment]
If I have dealias in dask.dataframe.optimize then yes, things seemed to run smoothly.  You might want to have the NYCTaxi dataset handy.  It's a nice thing to have around.  https://gist.github.com/mrocklin/c16c5c483b2b9859ded5

**Comment by jcrist** [comment]
Three possibilities:
- Some things are going through the scheduler still that don't pass the `istask` test for establishing the ntasks count
- The graph mutates after the first task is ran.
- Bug in my code somehow, somewhere

**Comment by mrocklin** [comment]
How about not maintaining state and just always using `len(state['finished']) / len(state['dependencies'])` or something like that

**Comment by jcrist** [comment]
Should be good now. I take back my commitment to also adding time threshold for this PR. I think I'm going to rework the design to not repeatedly spawn threads on every call start when I add that. The cost of spawning a thread is relatively low, but if people are just going to register a `ProgressBar` and use it for all computations then I'd like to avoid repeatedly creating threads. Should get that in tomorrow/early next week, but this should be merged in the meantime.

**Pull request merged**
