### PR TITLE
numpy_compat.divide uses np.divide

### LINKED ISSUE #391: dask.array aggregation results compute as scalars, not 0d arrays
On Python 2.7:
```
In [11]: da.mean(da.ones(4, chunks=4), axis=0)
Out[11]: dask.array<x_16, shape=(), chunks=(), dtype=float64>

In [9]: type(da.mean(da.ones(4, chunks=4), axis=0).compute())
Out[9]: numpy.float64
```

On Python 3.4:
```
In [4]: type(da.mean(da.ones(4, chunks=4), axis=0).compute())
Out[4]: float
```

For consistency between the pre- and post-computed results, these should arguably both be 0-dimensional numpy arrays, because there are no dask.array scalars (maybe there should be?). At the very least, the result should be the same type on both Python versions.

Why this is a problem? `float` cannot be indexed with `None`, which is used in `da.stack`:
```
# python 3.4
In [14]: x = da.ones(4, chunks=4)

In [15]: da.stack([x.mean(), x.mean()])
Out[15]: dask.array<stack-6, shape=(2,), chunks=((1, 1)), dtype=float64>

In [16]: da.stack([x.mean(), x.mean()]).compute()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-52554981f590> in <module>()
----> 1 da.stack([x.mean(), x.mean()]).compute()

/Users/shoyer/dev/dask/dask/array/core.py in compute(self, **kwargs)
    721     @wraps(compute)
    722     def compute(self, **kwargs):
--> 723         result, = compute(self, **kwargs)
    724         return result
    725

/Users/shoyer/dev/dask/dask/array/core.py in compute(*args, **kwargs)
    511     dsk = merge(*[arg.dask for arg in args])
    512     keys = [arg._keys() for arg in args]
--> 513     results = get(dsk, keys, **kwargs)
    514
    515     results2 = tuple(concatenate3(x) if arg.shape else unpack_singleton(x)

/Users/shoyer/dev/dask/dask/array/core.py in get(dsk, keys, get, **kwargs)
   1242     get = get or _globals['get'] or threaded.get
   1243     dsk2 = optimize(dsk, keys, **kwargs)
-> 1244     return get(dsk2, keys, **kwargs)
   1245
   1246

/Users/shoyer/dev/dask/dask/threaded.py in get(dsk, result, cache, **kwargs)
     52     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     53                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 54                         **kwargs)
     55
     56     return results

/Users/shoyer/dev/dask/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, start_callback, end_callback, **kwargs)
    460         if isinstance(res, Exception):
    461             raise type(res)(" Exception in remote process\n\n"
--> 462                 + str(res) + "\n\nTraceback:\n" + tb)
    463         state['cache'][key] = res
    464         finish_task(dsk, key, state, results)

TypeError:  Exception in remote process

'float' object is not subscriptable

Traceback:
  File "/Users/shoyer/dev/dask/dask/async.py", line 260, in execute_task
    result = _execute_task(task, data)
  File "/Users/shoyer/dev/dask/dask/async.py", line 243, in _execute_task
    return func(*args2)
  File "/Users/shoyer/dev/dask/dask/array/core.py", line 41, in getarray
    c = a[b]
```

This is the cause of recent build failures in xray on Python 3.4.

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #391

cc @jcrist does this miss something with np.divide?

cc @shoyer this seems to handle the mean type issue

### CODE REVIEW

**Comment by shoyer** [comment]
This does not fix `da.sum`, which never uses divide:
```
In [11]: da.sum(da.zeros(4, chunks=1))
Out[11]: dask.array<x_209, shape=(), chunks=(), dtype=float64>

In [12]: da.sum(da.zeros(4, chunks=1)).compute()
Out[12]: 0.0
```

This manifested itself in an xray bug: https://github.com/xray/xray/issues/457

More comprehensive tests for aggregation functions would probably be in order :)

**Comment by mrocklin** [comment]
Sorry for the delay in this.  On my system dask.array has equivalent performance to numpy on both Python 2.7 and 3.4

Do we want to break from numpy here?

```python
In [1]: import dask.array as da

In [2]: da.sum(da.zeros(4, chunks=1))
Out[2]: dask.array<x_2, shape=(), chunks=(), dtype=float64>

In [3]: da.sum(da.zeros(4, chunks=1)).compute()
Out[3]: 0.0

In [4]: import numpy as np

In [5]: np.sum(np.zeros(4))
Out[5]: 0.0

In [6]: type(_3)
Out[6]: numpy.float64

In [7]: type(_5)
Out[7]: numpy.float64

In [8]: import sys

In [9]: sys.version
Out[9]: '3.4.3 |Anaconda 2.1.0 (64-bit)| (default, Jun  4 2015, 15:29:08) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
```

```python
In [1]: import dask.array as da

In [2]: da.sum(da.zeros(4, chunks=1)).compute()
Out[2]: 0.0

In [3]: import numpy as np

In [4]: np.sum(np.zeros(4))
Out[4]: 0.0

In [5]: type(_2)
Out[5]: numpy.float64

In [6]: type(_4)
Out[6]: numpy.float64

In [7]: import sys

In [8]: sys.ver
sys.version       sys.version_info  

In [8]: sys.version
Out[8]: '2.7.10 |Anaconda 2.1.0 (64-bit)| (default, May 28 2015, 17:02:03) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
```

**Comment by shoyer** [comment]
The problem is that computing to a scalar (rather than a 0d array) breaks other dask.array functions, notably stack.

There is probably a similar bug lurking if you index enough to extract s scalar, too.

**Comment by mrocklin** [comment]
Should we resolve this at this stage or within functions like `stack`?

**Comment by shoyer** [comment]
My sense is that the sanest approach is to avoid the concept of dask.array scalars if possible (as Travis suggested in the other thread). This would suggest doing the fix at this stage.

On the other hand, numpy has a tendency to produce scalars from 0d arrays, even, for example, with ufuncs. So scalars will definitely creep in, even if only from user defined functions.

Maybe we should even do the fix in both places?

**Comment by mrocklin** [comment]
Well, dask.array doesn't have a concept of scalar.  At the dask level everything *is* and `Array`.

```python
In [1]: import dask.array as da

In [2]: da.sum(da.zeros(4, chunks=1))
Out[2]: dask.array<x_2, shape=(), chunks=(), dtype=float64>
```

It's only once we compute to numpy that this turns into a scalar.  Unless we want to special case this I hesitate to break with numpy conventions.

**Comment by mrocklin** [comment]
The failing example in #391 seems to work under this branch.  I've added a test that does this both for mean and for sum.

```python
In [1]: import dask.array as da

In [2]: x = da.ones(4, chunks=4)

In [3]: da.stack([x.mean(), x.mean()]).compute()
Out[3]: array([ 1.,  1.])
```

**Comment by shoyer** [comment]
> It's only once we compute to numpy that this turns into a scalar.

True, but that also means there is no way to tell the difference between something that will compute to a scalar and something that will compute to a 0d array, e.g., if I write `array.map_blocks(f)`, then my function `f` needs to be work on both scalars and 0d arrays. This is probably an OK compromise, even though I do find it surprising, but it should be noted somewhere.

> Unless we want to special case this I hesitate to break with numpy conventions.

We already broke with numpy conventions when we didn't implement a scalar type :).

**Comment by shoyer** [comment]
Looks like the castra test failed again -- I just retriggered Travis on your last commit and now things pass.

This will solve the immediate problem, but I'm still nervous about stack handling 0d arrays that actually evaluate to Python scalars properly. It turns out stack actually works fine for NumPy scalars because they support some indexing operations:
```
In [29]: np.float32(1)[None,]
Out[29]: array([ 1.], dtype=float32)
```

Hence we get stuff like this:
```
# you can only create arrays from numpy scalars, because you need
# shape to be defined
In [31]: x = da.from_array(np.float32(1), chunks=())

# this works fine with NumPy scalars
In [32]: da.stack([x, x]).compute()
Out[32]: array([ 1.,  1.], dtype=float32)

# convert to builtin scalars
In [33]: x = x.map_blocks(math.sin)

# and now it breaks
In [34]: da.stack([x, x]).compute()
TypeError
```

**Comment by mrocklin** [comment]
Hrm, I think that I'm ok with this.  Dask.array is very much about emulating numpy.  It turns out that numpy is self-consistent with things like slicing into scalars.  I think that by emulating NumPy's interface we cover a lot of the corner cases that they have historically identified.  I'm not sure how to expand beyond numpy in a systematic way.  If you have thoughts on how to accomplish this then I'm all ears.

I'm ok with dask.array failing on things that aren't numpy-like.  The messaging here can be fairly clear "use numpy things, not python things."

That being said, if other situations arise in practice then we should definitely revisit this.

**Comment by shoyer** [comment]
Yeah, my concern is that in general the ecosystem is not careful about returning numpy vs builtin scalars. For example, both bottleneck and numba return builtin scalars from aggregation functions:

Bottleneck:
```
In [6]: import bottleneck as bn

In [7]: import numpy as np

In [8]: bn.nanmean(np.arange(5))
Out[8]: 2.0

In [9]: type(bn.nanmean(np.arange(5)))
Out[9]: float
```

Numba:
```
In [10]: import numba

In [11]: @numba.jit
   ....: def mean2(x):
   ....:     return x.mean()
   ....:

In [12]: mean2(np.arange(5))
Out[12]: 2.0

In [13]: type(mean2(np.arange(5)))
Out[13]: float
```

**Comment by mrocklin** [comment]
What is the best way to handle these cases?  Do we need to put in checks in all functions?  Just in a few functions like `stack`?  I'm not sure how to go about solving this.

**Comment by shoyer** [comment]
> What is the best way to handle these cases? Do we need to put in checks in all functions? Just in a few functions like stack? I'm not sure how to go about solving this.

I wish I had a clean solution here. Stack seems like the most likely function to encounter Python scalars. Perhaps it's worth adding an `asarray` call in there if the input array is 0d.

**Comment by mrocklin** [comment]
@shoyer can you take a look at https://github.com/mrocklin/dask/commit/afb821344d532a40023ce8d78b6e1659d22a1fd4

This makes `concatenate3` robust to scalars.  This is the function that effectively does the `stack` after the call to `get`.

**Comment by shoyer** [comment]
That looks fine to me. I would not have guessed that `concatenate3` is where that logic lives :).

**Comment by mrocklin** [comment]
Great.  Merged.

**Comment by mrocklin** [comment]
This should be a fairly wide-reaching change.  Please let me know if an issue like #391 recurs.

**Pull request merged**
