### PR TITLE
API docs

### PR DESCRIPTION
**Pull request by mrocklin**
This is a curated alternative to #231 

@arve0 I'm fairly ignorant about sphinx.  If I'm doing something dumb then please speak up.

### CODE REVIEW

**Comment by minrk** [comment]
Supporting this: In both IPython and pyzmq, we used to autodoc everything by default, and consistently found this to be a mistake - publicizing private APIs, hiding the public API in the noise, etc.. PyZMQ switched over to hand-selected APIs a while ago, and IPython projects are starting to follow suit as part of the Big Split™. It has been a significant improvement so far.

**Comment by arve0** [comment]
@mrocklin `sphinx.ext.napoleon` adds support for numpy docstrings without installing extra packages (sphinx>=1.3).

@minrk By curiosity (I'm not familiar with API maintenance on larger projects), what are the reasons to have a private API without using the `_private` convention?

**Comment by minrk** [comment]
@arve0 our definition of private/public isn't always super clear, and can change over time. That shouldn't require renaming things. Automatically documenting everything enabled us to be lazy, and never really decide what's public and what's not. This has resulted in people depending on things we don't want preserve, and leaving us with no leg to stand on if we try to say "You shouldn't have been using that." forcing private APIs that we don't like into public APIs *because they were unintentionally documented as such*. Plus, there are whole classes of objects that aren't considered part of IPython's public API. This is the vast majority of IPython. Those classes shouldn't be included in the API docs, but it would be a bit silly to implement that as a few hundred underscores.

**Comment by arve0** [comment]
@minrk Thanks, well put! Must say this makes me think of package level dependency locking, but that's another topic.

**Comment by mrocklin** [comment]
OK, I've cleaned things up a bit.  I plan to merge these docs for dask.bag and see how the feel.  General suggestions heartily welcome.

**Comment by shoyer** [comment]
+1 on manually curated API docs.

**Pull request merged**
