### PR TITLE
from_array wraps getitems with calls to np.asarray

### LINKED ISSUE #105: dask should not assume indexing an input array creates a numpy.ndarray
Consider:
```python
import dask.array as da
import dask
import numpy as np

class Wrapper(object):
    def __init__(self, array):
        self.array = array
        self.shape = array.shape
        self.dtype = array.dtype

    def __getitem__(self, key):
        return Wrapper(self.array[key])
    
    def __array__(self, dtype=None):
        return np.array(self.array, dtype=dtype)

x = da.from_array(Wrapper(np.arange(5)), blockshape=(5,))
with dask.set_options(get=dask.get):
    (x + 1).compute()
```
```
TypeError: unsupported operand type(s) for +: 'Wrapper' and 'int'
```

Many wrappers classes created numpy arrays when indexed (it's often the simplest thing to do), but this is by no means always the case (e.g., consider wrapping an alternate implementation of dask arrays).

Thus, for the purposes of arithmetic, at least, input should be coerced to numpy arrays using `np.asarray`. It is probably a good idea to do this on all arrays as soon as the computation gets rolling, though this might have some unfortunate complications for fused indexing (#103).

### LINKED ISSUE #139: Should dask.array coerce eagerly evaluated input to numpy.ndarray?
This is a generalization of the specific issue in https://github.com/ContinuumIO/dask/issues/105

For example, if `array.compute()` is called on dask array wrapping an already lazy array, it can return the lazy array instead of computing the values.

Likewise, we run into trouble if we try to do computation on lazy arrays that don't support computation.

There are two possible solutions here. Either we can declare that:

1. All arrays passed to `da.from_array` should produce a "computable" array when indexed. This can be any arbitrary array object as long as it satisfies the required API (e.g., it could be a numpy MaskedArray or astropy.quantity), or...
2. Dask should always coerce the result of indexing an array passed to `from_array` to an numpy array, either with (a)  `np.asanyarray` or (b) `np.asarray`.

Option 2(b) will probably lead to the less unexpected behavior, but it will require a bit more work and be slightly less flexible. For example, it precludes cleverness like using a lazy "virtual" array that implements shortcuts for arithmetic (e.g., by offloading work on a remote server/backend outside of dask).

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #139
Fixes #105

We coerce slices of inputs array-like objects to numpy arrays if
they weren't already.

cc @shoyer

### CODE REVIEW

**Comment by shoyer** [comment]
How does this interact with fusing for repeated getitem calls? Poorly, I'm guessing...

**Comment by mrocklin** [comment]
Ah, indeed.

**Comment by mrocklin** [comment]
We can use rewriting to trickle `np.asarray` calls above getitems.  This starts to raise questions about the order in which different matching rules are applied.  @jcrist might have thoughts here.

**Comment by jcrist** [comment]
Just to clarify, we want all calls to `getitem` to return a numpy array. But we also want to fuse indexing to limit the amount of `getitem` calls on array-likes.

A super simple way to do this would be to write a new `getitem` like so:

```
def getitem(a, b):
    np.asarray(a[b])
```

This allows all the current rewriting to still work, while also getting the desired result. If you'd rather not do this, it can also be done with a fairly short rewrite function.

**Comment by mrocklin** [comment]
Redefining getitem would work.  Slightly inelegant but presumably fine and simple/robust.  It looks like asarray calls are in the microsecond range.

We could add copies of existing rules with np.asarrays injected.  We could add a rule that trickles np.asarray above getitems.  I'm generally curious about the performance characteristics of rewriting.  For example how does it scale with adding new patterns?

**Comment by jcrist** [comment]
`np.asarray` does some extra work it seems that we don't need here. This is significantly faster (ns range) for cases that are already instances of `ndarray`:
```python
def getitem(a, b):
    res = a[b]
    if isinstance(res, np.ndarray):
        return res
    else:
        return np.asarray(res)
```

There should be little to no performance penalty for increasing the size of the pattern set. If we were using deterministic nets, then matching for linear patterns would be linear in the size of the longest matching pattern. Since these are non-deterministic, the backtracking complicates things a bit. Best case lookup for the first match is still linear in the length of the pattern, and isn't penalized by adding more patterns.

If I were to do this with rewriting (I still think a custom getitem is better), I'd write patterns that move asarray above getitem, and apply that as a pass before merging indices.

**Comment by shoyer** [comment]
Writing a custom `getitem` seems like a fairly elegant solution to me, but I don't have strong feelings here either way.

Avoiding unnecessary calls to `asarray` strikes me as premature optimization, given the speed of `asarray` (~1us) and the overhead of the threaded scheduler (~1ms/task) . That said, I don't have a problem with it, but you'll need to use `type(res) is np.ndarray` to make it exactly replicate `np.asarray`.

**Comment by mrocklin** [comment]
My only concern about using our own getitem is that it specializes things.  Other people are likely to use `operator.getitem` so we'll need to point them to the special one.  But this does seem like the right path forward.

**Comment by jcrist** [comment]
> Other people are likely to use operator.getitem so we'll need to point them to the special one.

If other people use `operator.getitem` then we'd still have issues, as there'd be no call to `np.asarray`. In that case we'd be better off doing an insertion pass before calling, where `asarray` is inserted after every call to `getitem`.

**Comment by shoyer** [comment]
@mrocklin are you worried about other people who are contributing to dask.array? or other people using dask? Because I think this should probably only be a concern for the former.

I would be opposed in general to adding `asarray` following all `getitem` calls because the dask specification is a public API, and users will expect they can use getitem in their own code for other things.

**Comment by jcrist** [comment]
@shoyer : just to clarify, I wasn't arguing for that. I truly think this is best solved by a custom `getitem`, and all other options are overly complicated.

**Comment by mrocklin** [comment]
> @mrocklin are you worried about other people who are contributing to dask.array? or other people using dask? Because I think this should probably only be a concern for the former.

I'm concerned about developers people writing functions that manipulate the dicts directly.  They might use getitem.  The question I have now is "do we write optimizations that assume everyone uses `getarray`  (what I call our new getitem) or do we remain flexible to the mixed case?"

**Comment by mrocklin** [comment]
See latest commit for a solution that tries to handle the mixed case of both getitem and getarray

**Comment by jcrist** [comment]
> The question I have now is "do we write optimizations that assume everyone uses getarray...

I think this is more specific to dask array than to dask itself. Many functions expect `ndarray`, so inputs must be ensured to be of that type. The optimizations we write in `dask.array` are specific to ndarrays, and as such could have a "standard" themselves - namely that `getarray` is used to ensure `ndarray` output. So I don't see a problem with this.

Further, some optimizations may only apply to arrays,but other things can use `getitem` as well. An easy way to distinguish array access from other things like lists would be to use `getarray` for array access only.

That said, the approach your using here seems fine to me.

**Comment by shoyer** [comment]
Is it possible to write a test to verify that getitem fusing still happens properly?

**Comment by mrocklin** [comment]
Yes, that's possible.  Might not happen for a little bit.

**Comment by mrocklin** [comment]
> Is it possible to write a test to verify that getitem fusing still happens properly?

As of 4f120d9 two getitems fuse into a single getitem, not a getarray.

**Comment by mrocklin** [comment]
Anything left to do here?

**Comment by jcrist** [comment]
Looks good to me.

**Comment by shoyer** [comment]
Thanks @mrocklin !

**Pull request merged**
