### PR TITLE
TST: exhaustive (currently failing) tests for dask.array slicing

### PR DESCRIPTION
**Pull request by shoyer**
Indexing has a lot of edge cases. This PR adds tests for many more of them.

Here is the particular case that I caught this morning because it broke
one of my tests for xray (which yes, are currently running against dask
master):

    assert eq(x[:, [0, 1, 2]][[0, 1]], a[:, [0, 1, 2]][[0, 1]])

But note that a number of these other tests are also currently failing.

### CODE REVIEW

**Comment by mrocklin** [comment]
Awesome.  This may take some time but I'm looking forward to this.

**Comment by mrocklin** [comment]
This was news to me

```python
In [31]: X[0, :, [0]]
Out[31]: array([[ 1.,  1.,  1.,  1.,  1.]])

In [32]: X[0][:, [0]]
Out[32]: 
array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])
```

**Comment by shoyer** [comment]
@mrocklin if you recall that recent numpy-discussion about fancy vs orthogonal indexing... that was one of the main examples of how numpy's existing indexing is confusing/broken. I would prefer *not* to replicate it in `dask.array` :).

**Comment by mwiebe** [comment]
+1 for orthogonal indexing

**Comment by mrocklin** [comment]
Closing this for now.  This test is added and skipped in #159 .  Future issues should probably be particular about specific missing/wrong functionality.

**Pull request closed without merging**
