### PR TITLE
Update fold docs

### PR DESCRIPTION
**Pull request by mrocklin**
Continues on from #519 

cc @StuartAxelOwen

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging soon if no comments.

**Comment by StuartAxelOwen** [comment]
I would really love to use an example reducing function that's not just `(a, a) -> a`, just to demonstrate that it's possible.  What about something like:

```python
>>> bag.from_sequence(range(3)*5).fold(lambda agg, item: agg | {item}, lambda agg1, agg2: agg1 | agg2, initial=set()).compute()
set([0, 1, 2])
```

**Comment by mrocklin** [comment]
added

**Comment by StuartAxelOwen** [comment]
Looks good!

**Pull request merged**
