### PR TITLE
SVD code for tall-and-skinny matrices

### PR DESCRIPTION
**Pull request by marianotepper**

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good.  Will play around with it soon.

**Comment by mrocklin** [comment]
I found this interesting to look at

```python
In [1]: import dask.array as da

In [2]: import numpy as np

In [3]: x = np.random.random((50, 10))

In [4]: d = da.from_array(x, blockshape=(10, 10))

In [5]: u, s, v = da.linalg.svd(d)

In [6]: from dask.dot import dot_graph
f
In [7]: from toolz import merge

In [8]: dot_graph(merge(u.dask, s.dask, v.dask))
Writing graph to mydask.pdf
```

mydask

**Comment by mrocklin** [comment]
From what I can see this looks great.  The one thing I would recommend would be informative docstrings around `da.linalg.qr` and `da.linalg.svd` noting how they're used and their limitations.  I can do this though if you're feeling done.

**Comment by marianotepper** [comment]
Yes, the diagrams look interesting. I looked at them before submitting the
pull request. They really show the dependency on the centralized part of
the algorithm : a small-scale QR decomposition and and small-scale SVD
decomposition.

I can update the docstrings and then, if something's still missing, you can
complete with whatever you find necessary.

--
Mariano

**Comment by eriknw** [comment]
This is amazing!

**Comment by mrocklin** [comment]
OK, merging.  I'll fool around with the docstrings in master

**Pull request merged**
