### PR TITLE
fit/predict functions for scikit learn

### PR DESCRIPTION
**Pull request by mrocklin**
This builds on work by @PeterDSteinberg .  It leverages the `partial_fit` method of various sklearn classes, pushing blocks of dask arrays through this method sequentially.  This should allow large dask arrays to leverage a decent subset of scikit-learn relatively smoothly.

Example
-------

```python
>>> import dask.array as da
>>> X = da.random.random((10, 3), blockshape=(5, 3))   # very small (but potentially big!) data
>>> y = da.random.random(10, blockshape=(5,))

>>> from sklearn.linear_model import SGDClassifier  # some possibly online classifier
>>> sgd = SGDClassifier()

>>> da.learn.fit(sgd, X, y, classes=[1, 0])    # fit!
SGDClassifier(alpha=0.0001, class_weight=None, epsilon=0.1, eta0=0.0,
       fit_intercept=True, l1_ratio=0.15, learning_rate='optimal',
       loss='hinge', n_iter=5, n_jobs=1, penalty='l2', power_t=0.5,
       random_state=None, shuffle=False, verbose=0, warm_start=False)
```

This passes all of X and y through the classifier sequentially.  We can use the classifier as normal on in-memory data, consuming and producing numpy arrays.

```python
>>> import numpy as np
>>> sgd.predict(np.random.random((4, 3)))  # doctest: +SKIP
array([1, 0, 0, 1])
```

Or predict on a larger dataset, consuming and producing dask arrays.

```python
>>> z = da.random.random((400, 3), blockshape=(100, 3))
>>> da.learn.predict(sgd, z)  # doctest: +SKIP
dask.array<x_11, shape=(400,), blockdims=((100, 100, 100, 100),), dtype=int64>
```

I haven't actually used this code on anything non-trivial so I probably have some large conceptual gaps.  Feedback welcome.

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @chdoig who may have thoughts

**Comment by mrocklin** [comment]
It's also not clear how much value this has.  I suspect that most of the pain is around getting data into the array, not processing it through sklearn.

**Comment by PeterDSteinberg** [comment]
I'm with you Matthew (unclear of this code's role in this repo).  I think
it is mainly a demonstration for now.  We don't want to create something
where we just have to maintain the args, kwargs to all the classes of
sklearn.  I'm open to ideas.

On Fri, Apr 3, 2015 at 2:21 PM, Matthew Rocklin <notifications@github.com>
wrote:

> It's also not clear how much value this has. I suspect that most of the
> pain is around getting data into the array, not processing it through
> sklearn.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ContinuumIO/dask/pull/138#issuecomment-89423437>.
>



-- 
Peter Steinberg - Continuum Analytics
206 715 4492

**Comment by mrocklin** [comment]
This approach specifically doesn't tie itself to the sklearn api except for the existence of `partial_fit` and `predict` methods, which I think should be fairly stable.

**Comment by shoyer** [comment]
I like it! I can see this coupling well with tools like xray that will make it easier to create dask arrays.

**Comment by mrocklin** [comment]
@shoyer did you have something in mind?  I'd be curious about that.

**Comment by shoyer** [comment]
Not off hand, to be honest. But next time I'm futzing with a scikit-learn model...

**Comment by mrocklin** [comment]
Merging soon if no comment

**Pull request merged**
