### PR TITLE
inline function to inline constants or keys.  Also, toposort.

### PR DESCRIPTION
**Pull request by eriknw**

### CODE REVIEW

**Comment by eriknw** [comment]
We probably should find a better location for these functions.

**Comment by eriknw** [comment]
There are now two inline functions: `dask.async.inline` and `dask.core.inline`.  Thoughts on renaming?  `dask.async.inline_functions`?

**Comment by mrocklin** [comment]
Yeah, perhaps `dask.optimize.inline_constants` and `dask.optimize.inline_functions`?

**Comment by eriknw** [comment]
The `inline` in this function inlines more than just constants.  It can inline any set of keys.  If no keys are provided, then it inlines all constants.

**Comment by eriknw** [comment]
I like the `dask.optimize` namespace.

**Comment by mrocklin** [comment]
ah, ok.  `inline` and `inline_functions` then

**Comment by eriknw** [comment]
Renamed.  Let's reorganize the code in a separate PR.

**Comment by mrocklin** [comment]
+1

**Comment by mrocklin** [comment]
I'm having a hard time replicating this error locally.  Working on it.

**Comment by mrocklin** [comment]
Hrm, reran travis and the error seems to have disappeared.  For posterity it was an issue with `sx.mean(axis=0)`.

**Pull request merged**
