### PR TITLE
Callback docstring

### PR DESCRIPTION
**Pull request by mrocklin**
cc @jcrist  ok with this?  Merging soon.

### CODE REVIEW

**Comment by mrocklin** [comment]
I found myself repeatedly trying to figure out the API for each of the callbacks

**Comment by jcrist** [comment]
Looks good to me. A note about the ability to also subclass might be nice, but definitely isn't necessary.

**Comment by mrocklin** [comment]
Added.  I stole your example from the docs.

**Comment by jcrist** [comment]
Cool. Merging.

**Pull request merged**
