### PR TITLE
Provide support for __len__

### LINKED ISSUE #54: Support for __len__
NumPy enables `__len__` to return the shape at axis `0`. If the array is a dimensionless scalar, it will fail with `TypeError: len() of unsized object`. Hopefully, this is an easy add.

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes #54. Provides an easy way to get the `len` of a dask.

### CODE REVIEW

**Comment by jakirkham** [comment]
@mrocklin, here is an attempt to address this. I was going to add tests based off the ones for `shape`, but somehow missed them.

**Comment by mrocklin** [comment]
Awesome.  A test would be good.  I would probably just add an extra line to the tests for shape.

**Comment by jakirkham** [comment]
Right, so where are you testing `shape`? I seemed to have missed it.

**Comment by jakirkham** [comment]
I put them in `test_Array` if that's alright.

**Comment by mrocklin** [comment]
Looks good!   Thanks @jakirkham !  This is in.

**Comment by jakirkham** [comment]
Thanks.

**Pull request merged**
