### PR TITLE
Ghost

### PR DESCRIPTION
**Pull request by mrocklin**
Add overlapping functionality through ghost cells.

Computations like convolution of a filter/stencil across an image/array rely on knowing just a little bit about their neighboring blocks.  The `ghost` operation broadens each block by its neighbors so that we can then map a suitable function across these widened blocks in an embarrassingly parallel fashion.

TODO:

- [x] Nicely express common boundary conditions (reflect, periodic, constant, from_function)
- [x] Provide hook to block location in `map_blocks`

Example
-------

Ghosting
```python
    >>> import dask.array as da
       
    >>> x = np.arange(64).reshape((8, 8))
    >>> d = da.from_array(x, blockshape=(4, 4))
    >>> d.blockdims
    ((4, 4), (4, 4))

    >>> g = da.ghost.ghost(d, depth={0: 2, 1: 1}, kind={0: 100, 1: 'reflect'})
    >>> g.blockdims
    ((8, 8), (6, 6))

    >>> np.array(g)
    array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
           [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
           [  0,   0,   1,   2,   3,   4,   3,   4,   5,   6,   7,   7],
           [  8,   8,   9,  10,  11,  12,  11,  12,  13,  14,  15,  15],
           [ 16,  16,  17,  18,  19,  20,  19,  20,  21,  22,  23,  23],
           [ 24,  24,  25,  26,  27,  28,  27,  28,  29,  30,  31,  31],
           [ 32,  32,  33,  34,  35,  36,  35,  36,  37,  38,  39,  39],
           [ 40,  40,  41,  42,  43,  44,  43,  44,  45,  46,  47,  47],
           [ 16,  16,  17,  18,  19,  20,  19,  20,  21,  22,  23,  23],
           [ 24,  24,  25,  26,  27,  28,  27,  28,  29,  30,  31,  31],
           [ 32,  32,  33,  34,  35,  36,  35,  36,  37,  38,  39,  39],
           [ 40,  40,  41,  42,  43,  44,  43,  44,  45,  46,  47,  47],
           [ 48,  48,  49,  50,  51,  52,  51,  52,  53,  54,  55,  55],
           [ 56,  56,  57,  58,  59,  60,  59,  60,  61,  62,  63,  63],
           [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
           [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])
```

Mapping

```python
>>> from scipy.ndimage import gaussian_filter
>>> def func(block):
    return gaussian_filter(block.astype('f4'), 1)

>>> filt = g.map_blocks(func)
>>> filt.blockdims  # Still fatter than we would like
((8, 8), (6, 6))

>>> result = da.ghost.trim_internal(filt, {0: 2, 1: 1})
>>> result.blockdims  # Back to original size
((4, 4), (4, 4))
```

### CODE REVIEW

**Comment by shoyer** [comment]
Ghost also provides a mechanism for writing generic moving window functions, yes? Though of course, it's much more efficient to use explicitly rolling algorithms when possible (e.g., for mean, median).

**Comment by mrocklin** [comment]
Yes, this would support moving window functions.  It actually might not be that much slower as long as your per-block function is efficient.  We're really only wasteful on the boundaries which, for moderate dimension, can be relatively small.

**Comment by shoyer** [comment]
Well, rolling_mean can be calculated in time O(n) if you keep track of the cumulative sum, rather than O(n * w) if you use the naive approach where n is the number of elements and w is the window size. But I agree, this is useful.

**Comment by mrocklin** [comment]
Right, if you give me a `rolling_mean` function that can operate on a numpy array in `O(n)` (for block size n) then ghosting can give you a `rolling_mean`  function that can operate on a dask array in `O(n*k + d*k)` for block size n, k blocks, with window size d.  Ghosting lets us treat a lot of almost-embarrassingly parallel operations as embarrassingly parallel at the cost of a memory copy.

**Comment by mrocklin** [comment]
I've updated the header comment with a new API for the `ghost` function that takes inputs for boundary conditions.  I'm decently happy with this interface (though we should extend it to more kinds of boundaries like `fromfunction`).  

Performance issue.  We're doing a lot of `x -> x[:, :]` on all of the internal blocks a few times.  It's probably best to clean this up with an optimization pass that is more general than just the ghosting work.

**Comment by mrocklin** [comment]
I think that this is about ready.  If anyone intends to review or give feedback please let me know.  If anyone has questions about how things work or how to use this after reading the [doc page](https://github.com/mrocklin/dask/blob/ghost/docs/source/ghost.rst) that would be very helpful to help me better clarify things for others.

If no one gets back to me about this in the next few hours I'll go ahead and merge.

**Pull request merged**
