### PR TITLE
Add appveyor support

### LINKED ISSUE #371: Use appveyor for windows testing
http://www.appveyor.com/

It would be nice to have continuous testing of windows as well as the linux support that travis.ci provides.

### PR DESCRIPTION
**Pull request by jcrist**
Build script works fine, everything gets setup and run properly. Just need to turn on appveyor for master.
Currently only testing on Python 2.7 + Win32 and Python 3.4 + Win64.

Right now I'm seeing an error on Python 2.7 + Win32 in a dask.distributed test ([test log](https://ci.appveyor.com/project/jcrist/dask/build/1.0.4/job/urb0le3a4x96pful)). Not sure if it's periodic, a python 2.7 + windows bug, or a python + Win32 bug. Would be easier to figure out if I had access to a windows machine.

Fixes #371.

### CODE REVIEW

**Comment by mrocklin** [comment]
To the extent that I can judge this looks good to me.  The failing test is known to cause intermittent failures.

**Comment by ogrisel** [comment]
You might want to configure configure a github webhook to an appveyor account that has push rights to the dask github repo and then select "Let me select individual events." then "Pull requests" & "Push" events on the github webhooks configuration. This way you will get both travis and appveyor green ticks on the pull requests.

**Comment by mrocklin** [comment]
@jcrist what needs to be done to finish this?

**Comment by jcrist** [comment]
Need to activate appveyor on the branch, and possibly figure out if that windows error is consistent. I think the yaml is good though.

**Comment by ogrisel** [comment]
For scikit-learn I created a github account named `sklearn-ci`, gave it push right to the scikit-learn repo and used that to configure the appveyor process. This way you can give the password to that account to several people if they need to do some admin with it (to get a bus factor > 1).

**Comment by jcrist** [comment]
Appveyor seems to be too slow right now for practical use. Last build took 45 minutes from push (with nothing else in the queue), while tests only take 1-2 min to run on my machine. Closing this for now.

**Comment by shoyer** [comment]
@jcrist do you still have your branch somewhere? It would be nice to test this again.

**Comment by jcrist** [comment]
Sure, I can start it back up today and see if things have changed. What's the turnaround time on appveyor for xray?

**Comment by shoyer** [comment]
Appveyor build start up almost immediately, but they aren't run concurrently like on Travis. So it's roughly 5 minutes for the first test to pass, about another 5 minutes for the second. (I run two builds on Appveyor.) It's pretty reasonable, though. It's nice to just have the tests running automatically, even if sometime I'll merge PRs after the Travis tests but before Appveyor finishes.

**Comment by cowlicks** [comment]
The Appveyor $19/mo offers a "super fast build environment" but only one concurrent job. http://www.appveyor.com/pricing

**Comment by shoyer** [comment]
I believe they now offer that "super fast build environment" for free for
open source projects. In the past, they had an extremely slow build only
for open source stuff.

**Comment by izaid** [comment]
@shoyer Do you have a link to that? DyND has "super fast" Appveyor (and it is really fast, even if it is just one at a time), but we pay.

**Comment by shoyer** [comment]
http://www.appveyor.com/blog/2015/06/23/new-oss-build-environment-and-xamarin-support

**Pull request closed without merging**
