### PR TITLE
getarray handles newaxis for non-numpy arrays

### PR DESCRIPTION
**Pull request by mrocklin**
Previously computations that uesd `np.newaxis` on top of array-like
objects like `h5py.Datasets` that didn't support it we got a runtime
error.  This offloads newaxis handling to the `getarray` function which
protects the downstream array objects from having to implement this.

### CODE REVIEW

**Comment by shoyer** [comment]
excellent, this should be useful

**Comment by mrocklin** [comment]
Already has been :)

**Comment by shoyer** [comment]
Another approach would be to simply map indexing with `np.newaxis` into a call to `da.stack`. That way it's all in the dask graph, instead of being buried in `getarray`. I suspect this would work better with optimization, for example.

**Comment by JDWarner** [comment]
For what it's worth, I didn't realize until this PR that dask supported `np.newaxis` so I worked around by using `da.stack` as @shoyer describes after a little experimentation and graph introspection.

**Comment by mrocklin** [comment]
The problem isn't necessarily restricted to `da.stack`.

**Pull request merged**
