### PR TITLE
Support aliases in dot visualization

### PR DESCRIPTION
**Pull request by mrocklin**
```python
In [1]: def f(*args): pass

In [2]: from dask.dot import dot_graph

In [3]: dot_graph({'x': 1, 'y': (f, 'x'), 'z': 'y'})
Writing graph to mydask.pdf
```

mydask

### CODE REVIEW

**Comment by mrocklin** [comment]
I also reverse the order of the arrows

**Comment by mrocklin** [comment]
Merging soon if no comment

**Comment by shoyer** [comment]
I'm optimistic this will fix my dot graphs for xray :).

I like the switched arrow direction -- they follow the data flow now, which seems more intuitive to me

**Comment by shoyer** [comment]
Indeed, it works now! Here's a beautiful image of resampling monthly files with 6 hourly data to a 15 day moving mean:

mydask

**Comment by mrocklin** [comment]
Whoa, awesome

**Comment by mrocklin** [comment]
I <3 dot

**Pull request merged**
