### PR TITLE
Add fuse function (see #18) to combine linear operations into one.

### PR DESCRIPTION
**Pull request by eriknw**
Also added `subs` method (used by `fuse`) to substitute values in a task.

Needs documentation.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for pushing.  I'll play with it and see if I can break it.

**Comment by mrocklin** [comment]
Example
-------

```Python
In [1]: from dask.bag import Bag

In [2]: from dask.core import fuse

In [3]: d = {('x', i): (range, 5) for i in range(3)}

In [4]: b = Bag(d, 'x', 3)

In [5]: dsk = b.map(lambda x: x + 1).filter(lambda x: x > 2).sum().dask

In [6]: dsk
Out[6]: 
{('x', 1): (range, 5),
 ('x', 2): (range, 5),
 ('bag-3', 2): (<function sum>, ('bag-2', 2)),
 ('bag-2', 1): (list, (filter, <function __main__.<lambda>>, ('bag-1', 1))),
 ('bag-3', 0): (<function sum>, ('bag-2', 0)),
 ('bag-2', 0): (list, (filter, <function __main__.<lambda>>, ('bag-1', 0))),
 ('bag-1', 2): (list, (map, <function __main__.<lambda>>, ('x', 2))),
 ('bag-2', 2): (list, (filter, <function __main__.<lambda>>, ('bag-1', 2))),
 ('bag-1', 0): (list, (map, <function __main__.<lambda>>, ('x', 0))),
 ('bag-1', 1): (list, (map, <function __main__.<lambda>>, ('x', 1))),
 ('bag-3', 1): (<function sum>, ('bag-2', 1)),
 ('x', 0): (range, 5),
 'bag-4': (<function sum>, [('bag-3', 2), ('bag-3', 1), ('bag-3', 0)])}

In [7]: fuse(dsk)
Out[7]: 
{ 'bag-4': (<function sum>, [('bag-3', 2), ('bag-3', 1), ('bag-3', 0)]),
 ('bag-3', 2): (<function sum>,
  (list,
   (filter,
    <function __main__.<lambda>>,
    (list, (map, <function __main__.<lambda>>, (range, 5)))))),
 ('bag-3', 1): (<function sum>,
  (list,
   (filter,
    <function __main__.<lambda>>,
    (list, (map, <function __main__.<lambda>>, (range, 5)))))),
 ('bag-3', 0): (<function sum>,
  (list,
   (filter,
    <function __main__.<lambda>>,
    (list, (map, <function __main__.<lambda>>, (range, 5))))))}
```

**Comment by mrocklin** [comment]
If you run tests alongside my bag branch then this pops up

```Python
-> arg = subs(arg, key, val)
(Pdb) print arg
(<function join at 0x7f486dd960c8>, <function iseven at 0x7f48696c2b90>, [1, 2, 3], <function isodd at 0x7f48696c2c08>, ('x', 2))
(Pdb) print key
('x', 2)
(Pdb) print val
(<built-in function range>, 5)
(Pdb) print subs(arg, key, val)
*** TypeError: 'int' object has no attribute '__getitem__'
(Pdb) down
> /home/mrocklin/workspace/dask/dask/core.py(227)subs()
-> arg = [subs(x, key, val) for x in arg]
(Pdb) down
> /home/mrocklin/workspace/dask/dask/core.py(223)subs()
-> for arg in task[1:]:
(Pdb) print task
1
```

This was the offending dask

```Python
(Pdb) pprint(data)
{('bag-30', 0): (<type 'list'>,
                 (<function join at 0x7f486dd960c8>,
                  <function iseven at 0x7f48696c2b90>,
                  [1, 2, 3],
                  <function isodd at 0x7f48696c2c08>,
                  ('x', 0))),
 ('bag-30', 1): (<type 'list'>,
                 (<function join at 0x7f486dd960c8>,
                  <function iseven at 0x7f48696c2b90>,
                  [1, 2, 3],
                  <function isodd at 0x7f48696c2c08>,
                  ('x', 1))),
 ('bag-30', 2): (<type 'list'>,
                 (<function join at 0x7f486dd960c8>,
                  <function iseven at 0x7f48696c2b90>,
                  [1, 2, 3],
                  <function isodd at 0x7f48696c2c08>,
                  ('x', 2))),
 ('x', 0): (<built-in function range>, 5),
 ('x', 1): (<built-in function range>, 5),
 ('x', 2): (<built-in function range>, 5)}
```

It looks like this part of `subs` expects that all lists are lists of tasks

        elif isinstance(arg, list):
            arg = [subs(x, key, val) for x in arg]

perhaps subs should have an `if not istask(task): return task` branch.

**Comment by eriknw** [comment]
Right on about `subs` missing a non-task branch.  Should be fixed.

**Comment by eriknw** [comment]
Fail case?
```python
>>> d = {'a': 1, 'b': (inc, 'a'), 'c': (add, 'b', 'b')}
>>> fuse(d)
{'c': (add, (inc, 1), (inc, 1))}
```
I would expect the following
```python
>>> fuse(d)
{'b': (inc, 1), 'c': (add, 'b', 'b')}
```
This occurs because we don't use the multiplicity of each dependent (it is unavailable from `get_dependencies`).  I think I'll add a keyword to `get_dependencies`, but I can make a new function if you prefer.

**Pull request merged**
