### PR TITLE
Add DataFrame.iloc

### PR DESCRIPTION
**Pull request by sinhrks**
This PR add ``iloc`` to ``_Frame``.

```
import pandas as pd
import dask.dataframe as dd
df = dd.from_pandas(pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]}), 2)
df.compute()
#    x  y
# 0  1  5
# 1  2  6
# 2  3  7
# 3  4  8

df.iloc[1].compute()
# x    2
# y    6
# Name: 1, dtype: int64

df.iloc[1:3].compute()
#    x  y
# 1  2  6
# 2  3  7
```

``iloc`` with ``Series`` is not supported as the same as ``pandas``.

```
pd.DataFrame([1, 2, 3]).iloc[pd.Series([True, False, True])]
# NotImplementedError: iLocation based boolean indexing on an integer type is not available
```

### CODE REVIEW

**Comment by mrocklin** [comment]
Nice solution.  I find myself conflicted here.  This achieves functionality that people will undoubtedly want but which is also fairly slow.  All `iloc` queries will result in a full scan over the data just to create the graph.  Do we support this because we can or exclude it to wean users off of it?

**Comment by mrocklin** [comment]
I don't have an answer to this question.  I suspect that the Pandas developers have a better understanding than I do of what is valuable and not valuable.

**Comment by sinhrks** [comment]
Thanks for your consideration. 

> All iloc queries will result in a full scan over the data 

Not sure I could understand what you mean, but the slowness also applies to ``loc``? Followings are dask graphs of related part.

```
import pandas as pd
import dask.dataframe as dd
df = dd.from_pandas(pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                                  'y': [5, 6, 7, 8, 9, 10, 11, 12, 13]}), 4)
df
df.loc[3].dask
#  ...
#  Index: [], ('loc-element-29', 0): (<function dask.dataframe.core.<lambda>>,
#   ('from_pandas-2', 1))}

df.iloc[3].dask
#  ...
#  Index: [], ('iloc-element-30', 0): (<function dask.dataframe.core.<lambda>>,
#   ('from_pandas-2', 1))}

df.loc[3:6].dask
#  ...
#  Index: [], ('loc-slice-39', 0): (<function dask.dataframe.core._loc>,
#   ('from_pandas-2', 1),
#   3,
#   None), ('loc-slice-39', 1): (<function dask.dataframe.core._loc>,
#   ('from_pandas-2', 2),
#   None,
#   6)}

df.iloc[3:6].dask
#  Index: [], ('iloc-slice-40', 0): (<function dask.dataframe.core._iloc>,
#   ('from_pandas-2', 1),
#   0,
#   None), ('iloc-slice-40', 1): (<function dask.dataframe.core._iloc>,
#   ('from_pandas-2', 2),
#   None,
#   0)}
```

I think ``iloc`` is useful to split some part of data based on its number, and there are following options. 

- Not support it
- Show ``PerformanceWarning`` like ``pandas``
- Not show warning, describe a note in the doc

@cpcloud @shoyer TomAugspurger Any opinions?

**Comment by shoyer** [comment]
> Not sure I could understand what you mean, but the slowness also applies to loc? 

The difference is that dask dataframes are partitioned by label, not chunk size. Thus, you need to compute/load the entire dataframe to know integer positions. This is at odds with the general convention that indexing is cheap, because it only requires looking up a small portion of the data. In contrast, with `.loc`, you can do label based lookup without computing the entire dataframe.

So, I would lean against including `.iloc` unless there are strong use cases..

**Comment by TomAugspurger** [comment]
This touches an important API decision for dask dataframe: how to balance matching the pandas API with the differing goals of dask. IMO we should be slow to add methods that don't fit well with dask's design.

**Comment by mrocklin** [comment]
Nice examples @sinhrks .  The performance difference between `iloc` and `loc` in this case is that the cost to produce the graph for `loc` operations is almost free because we know from the `divisions` metadata everything we need to construct the graph.  In the `iloc` case you have a call to `compute` in `_idivisions`, so the construction of the graph will trigger a full computation.  Usually we try to make graph construction free; we don't always succeed though.  Operations like `set_index` do trigger evaluation; we should try to keep these operations very rare though. 

All of the options you suggest seem reasonable to me; I don't have a strong opinion here.

**Comment by sinhrks** [comment]
Thanks.,I understood the issue. Based on @shoyer and @TomAugspurger 's suggestion, pls leave it until someone strongly request the feature.

**Comment by mrocklin** [comment]
OK.  Closing this for now.  Lets keep this PR in mind if someone asks for this in the future.

**Comment by philastrophist** [comment]
Just a quick question from someone who uses iloc a lot with pandas dataframes:

I'm just wondering why this is a problem: iloc indexes based on the order and loc indexes based on the label. A label corresponds to an original index so surely we can partition based on either and use a lookup table to map the other? 

For example if we keep the current procedure (partition on labels) can there not be a list of tuples (`[(label, index)]`)? 

Maybe I just don't understand the issue properly since I've on just started using dask+distributed, but it's a pandas-feature I use often and its a shame that I have to roughly implement it myself with a locally-bound lookup table.

**Comment by mrocklin** [comment]
It's hard to propagate count information lazily.  

For example with operations like groupby, set_index, join, query, etc.. we can't determine how many values are in each partition without actually performing the computation and looking at all of the values.

**Comment by philastrophist** [comment]
I think I'll look at the code to get a better idea of how this works.
 But isn't the number of values known? Since we partitioned them at instantiation and track subsequent operations' output?

**Comment by mrocklin** [comment]
For some operations, like `query`, the number of values depends on the values themselves.  We would need to do all of the work of the computation in order to maintain this metadata.  

    df = df.query('x > 0')

In the case above we genuinely need to know how many positive x values we had to keep track of the length metadata.  This kills laziness.

**Pull request closed without merging**
