### PR TITLE
add foldby docs for combine function

### PR DESCRIPTION
**Pull request by mrocklin**
@cowlicks suggestions on how to improve this?

### CODE REVIEW

**Comment by cowlicks** [comment]
The way I understand `binop` and `combine` isn't really conveyed here, basically the way I understand it.

I think a more clear example would be useful, hang on.

**Comment by cowlicks** [comment]
Maybe the "binop" argument should be called "partition reduction" it is basically given each piece that corresponds to one part of group and one partition...? The First argument to this binop is the "initial" argument, and the second is, at leas in my example iterable. It doesn't even really seem to be a binop.

**Comment by cowlicks** [comment]
```python
In [80]: data = [('a', (1, 2)), ('b', (2, 3)), ('a', (3, 4, 5)), ('c', (2,)), ('c', (3, 0)), ('d', (0,)), ('d', (2,))]

In [81]: b = db.from_sequence(data)

In [82]: def partition_reduction(total, x):                                                                           
    return total + sum(x[1])
   ....: 

In [83]: from operator import mul

In [84]: b.foldby(lambda (key, value): key, partition_reduction, 0, combine=mul).compute()
Out[84]: [('a', 36), ('c', 6), ('b', 5), ('d', 0)]
```
Is the same as:
```python
In [94]: grouped = dict(b.groupby(lambda (key, value): key))  # group by the key

In [95]: grouped
Out[95]: 
{'a': [['a', [3, 4, 5]], ['a', [1, 2]]],
 'b': [['b', [2, 3]]],
 'c': [['c', [2]], ['c', [3, 0]]],
 'd': [['d', [0]], ['d', [2]]]}

In [96]: for k, v in grouped.iteritems():
    
    print(k, reduce(mul, [reduce(add, part[1], 0) for part in v]))
   ....:     
('a', 36)
('c', 6)
('b', 5)
('d', 0)
```

**Comment by mrocklin** [comment]
Ah, the binop is not given a group, it is given a single element that belongs to that key

```python
In [1]: seq = [('a', 1), ('b', 2), ('a', 3), ('a', 4)]

In [2]: def key(x):
   ...:         return x[0]
   ...: 

In [3]: def binop(total, x):
   ...:         return total + x[1]
   ...: 

In [4]: from toolz import reduceby

In [5]: reduceby(key, binop, seq, 0)
Out[5]: {'a': 8, 'b': 2}
```

**Comment by shoyer** [comment]
Hadoop's mapreduce uses "combine"/"reduce" for what you call "binop"/"combine". This could be a bit confusing.

Instead of "combine"/"binop", Spark appears to use accumulators.

Using either of these pre-existing terminologies might be preferable.

**Comment by mrocklin** [comment]
The analogous pyspark function to `Bag.foldby` would be `RDD.combineByKey`, which has the following signature.

    pyspark.RDD.combineByKey(self, createCombiner, mergeValue, mergeCombiners, numPartitions=None)

Where the following names roughly map from pyspark to dask.bag

    createCombiner - default
    mergeValue - binop
    mergeCombiners - combine

I'm not confident that this concept exists in straight MapReduce.  My experience with MapReduce is that you tend to write code that expects an iterator per group and you expect the entire group in one shot, obviating the need for a combine step.

**Comment by mrocklin** [comment]
Planning to merge these soon if no comment.  I don't mean to end discussion on the function names (I agree that we can find better) but this just adds docs to the existing ones.  It should be easy to change those names in the docs easily.

**Pull request merged**
