### PR TITLE
Add dask.array.from_func

### LINKED ISSUE #344: Create a dask array from a function call
The other day, I needed to create a dask array by calling a function that creates a numpy array.  The way I did this is by constructing `LazyArray` objects and then calling `from_array` on them:
```python
class LazyArray(object):
    def __init__(self, func, shape, dtype):
        self.func = func
        self.shape = shape
        self.dtype = dtype

    def __getitem__(self, key):
        return self.func()[key]
```

I also considered just constructing the array directly using the `da.Array` constructor, but decided not to bother because I didn't want to worry about picking a unique name.

This seems likely to be a fairly common pattern, so it would be nice to have a convenience function. In my case, I had written a function to parse a strange file format, but I can also imagine this as a more general entry point for dask array (e.g., from computationally expensive functions). Perhaps `da.from_func(func, shape, dtype)`?

### PR DESCRIPTION
**Pull request by shoyer**
Fixes #344

@mrocklin I think this doctest should work -- anything else I should test?

### CODE REVIEW

**Comment by eriknw** [comment]
Don't forget to import `from_func` in `dask/array/__init__.py`.

Would it be reasonable for `dtype` be optional?

It's a little weird that `from_func` and `fromfunction` both exist in `dask.array`.  Just sayin'.

I like `from_func`.  I think it is especially convenient when combined with `concatenate` and `stack`.  These can probably make the "complex case" easier for a lot of use cases, so it'll probably make sense to update the "Array Creation - Complex Case" in the documentation at some point.

**Comment by shoyer** [comment]
OK, looks like I shouldn't skip writing unit tests :).

I made `dtype` an optional argument.

Indeed, this works very well with concatenate and stack. That's exactly how I'm using dask.array currently -- I've created a dask array where each chunk is actually a large chunk of data sitting on Amazon S3.

**Comment by mrocklin** [comment]
As a reminder you probably *will* want to specify dtype as often as possible.  This will otherwise trigger a computation the next time something wants to compute a dtype.

**Comment by shoyer** [comment]
> As a reminder you probably will want to specify dtype as often as possible. This will otherwise trigger a computation the next time something wants to compute a dtype.

Indeed, this is why I made dtype a required argument originally. Maybe it's better to force a user  to explicitly supply `dtype=None` if they want to skip it?

**Comment by shoyer** [comment]
The other thing possibly worth emphasizing in docs is that if you try something like the following, it will silently fail:
```python
da.stack([da.from_func(lambda: make_array(xi), shape) for xi in x])
```

Why? Because the lambda does not capture the value of `xi` from the closing scope. So every array you stack ends up creating its data with the last value of `xi`.

Instead, you need to use a partial or a class with a `__call__` method.

**Comment by cowlicks** [comment]
@shoyer did you have a use case in mind? I can't tell from the docstring what this would be used for. Also +1 for a name change.

**Comment by shoyer** [comment]
> @shoyer did you have a use case in mind? I can't tell from the docstring what this would be used for.

The use case is funny, custom applications where you can write a function to create an array, but don't have an indexable array already. Using `from_array` is easier and less verbose than creating the dask graph manually.

For example, I could use `from_array` to process image files (e.g., `.jpg`), given a function that loads one image at a time from disk into memory.

Once you have the dask arrays, the next step would typically be to concatenate and stack them. This can certainly be done straightforwardly by creating the dask graph directly, but it's nice to be able to use higher level API like `stack` and `concatenate`.

> Also +1 for a name change.

Hmm. I've never used `np.fromfunction` before... and it turns out numpy documents it poorly and/or incorrectly ([see here](http://stackoverflow.com/a/18709458/809705) for a better explanation). @mrocklin it looks like you were intending to use `fromfunction` for something related to ghosting? (It was added in #51.)

I agree that name conflicts are bad, but it would also be nice to have something that resembles `from_array`. Any ideas? `from_thunk` would be more literal but probably also more confusing.

**Comment by mrocklin** [comment]
Yes, `fromfunction` was to be used for custom boundary conditions while ghosting.

I suggest that we keep what is currently called `from_func` out of the main `da` namespace and use it from `da.core` until it has a bit more use.

**Comment by mrocklin** [comment]
@shoyer still interested in this?

**Comment by shoyer** [comment]
Yep, still interested in this, though we haven't figured out the right name yet. I'm not sure how much it will help to merge this before we add it to the API.

I think I'm going to add `args` and `**kwargs` arguments to this function, specifically to discourage calling it using a `lambda` with variables set in loop (which breaks). `args` and `**kargs` will be used to create a `partial` object inside `from_func` if they are supplied.

**Comment by mrocklin** [comment]
We should probably add args, kwargs to other similar functions throughout the API

**Comment by cpcloud** [comment]
> Instead, you need to use a partial or a class with a __call__ method.

a slightly less heavyweight solution is to use a keyword argument:

```python
da.stack([da.from_func(lambda xi=xi: make_array(xi), shape) for xi in x])
```

**Comment by shoyer** [comment]
I added `args`, `kwargs` and another example, and this is no longer in the top level `dask.array` namespace.

I think this is ready to be merged? If someone else goes looking for this, I suggest we try to come up with a better name and add it to the official API.

**Comment by mrocklin** [comment]
Looks good to me

**Comment by shoyer** [comment]
OK, I will merge unless there are any objections.

**Comment by mrocklin** [comment]
Beat you to it.

**Pull request merged**
