### PR TITLE
Finish PR #141: remove into code from dask.array

### PR DESCRIPTION
**Pull request by cowlicks**
This currently has a test... abortion? in `test_blaze`, it is probably from a numba interaction since it is spitting out stuff about the llvm. I'm not sure how to fix this.

### CODE REVIEW

**Comment by mrocklin** [comment]
Probably we don't fix it here; this is probably something to fix in Blaze (cc @cpcloud ).  We xfail (or comment out if xfailing still causes the error (which it probably would)).

**Comment by mrocklin** [comment]
An alternative would also be to move the `dask.array.blaze` code also over to `blaze.compute.dask` and deal with it there.  That has to happen anyway.

**Comment by cowlicks** [comment]
I don't want to xfail it, since test (`test_compute`) tests a bunch of blaze expressions. The one which is crashing the llvm is `sx.mean(axis=0)`.

I made a minimal example script: https://gist.github.com/cowlicks/e922b7bde6a26460e277

**Comment by cowlicks** [comment]
Currently on hold due to Blaze issue [#1030](https://github.com/ContinuumIO/blaze/issues/1030)

**Comment by mrocklin** [comment]
I've removed this in #160

**Pull request closed without merging**
