### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### ContinuumIO/dask now has a Chat Room on Gitter

@mrocklin has just created a chat room. You can visit it here: [https://gitter.im/ContinuumIO/dask](https://gitter.im/ContinuumIO/dask?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/ContinuumIO/dask?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by cowlicks** [comment]
:+1:

**Comment by cowlicks** [comment]
The preview [here](https://github.com/gitter-badger/dask/tree/gitter-badge) looks good.

**Comment by mrocklin** [comment]
Not sure I actually want to maintain a chat room yet.  Fooling around with their interface causes them to issue this PR.

**Comment by shoyer** [comment]
Yeah, the automatic PR issuing is an anti-feature IMO. That said, a chat room can be handy sometimes (I'm usually lurking in the pandas room).

**Comment by mrocklin** [comment]
OK, lets give this a shot for a while.  I think I've set gitter up to notify me on all messages.  Other lurkers heartily welcome.

Fixed in https://github.com/ContinuumIO/dask/commit/698eafa2d42157edf5f913833dd2aad90bc98a5f

**Pull request closed without merging**
